import { Project } from "@/types/project";

export const MOCK_PROJECTS: Project[] = [
  {
    id: "proj-1",
    name: "Client Work",
    description: "Active client engagements, deliverables, and relationship management across all accounts.",
    status: "on_track",
    priority: "critical",
    progress: 65,
    milestones: [
      { label: "Q4 report delivered", done: true },
      { label: "Partnership proposal sent", done: true },
      { label: "Contract renewal signed", done: false },
      { label: "Client review meeting", done: false },
    ],
    nextMilestone: "Contract renewal signed",
    lastUpdated: new Date(Date.now() - 2 * 3600000).toISOString(),
    color: "--brain-teal",
  },
  {
    id: "proj-2",
    name: "Product Development",
    description: "Building and shipping the core product — features, design, and technical infrastructure.",
    status: "at_risk",
    priority: "high",
    progress: 40,
    milestones: [
      { label: "MVP feature freeze", done: true },
      { label: "Landing page live", done: false },
      { label: "Beta launch", done: false },
      { label: "Analytics integration", done: false },
    ],
    nextMilestone: "Landing page live",
    lastUpdated: new Date(Date.now() - 5 * 3600000).toISOString(),
    color: "--brain-blue",
  },
  {
    id: "proj-3",
    name: "Finance & Admin",
    description: "Accounting, taxes, invoicing, and operational compliance across the business.",
    status: "on_track",
    priority: "medium",
    progress: 50,
    milestones: [
      { label: "GST issue resolved", done: false },
      { label: "Q4 books closed", done: true },
      { label: "Accountant sync", done: false },
    ],
    nextMilestone: "GST issue resolved",
    lastUpdated: new Date(Date.now() - 8 * 3600000).toISOString(),
    color: "--brain-amber",
  },
  {
    id: "proj-4",
    name: "Growth Experiments",
    description: "Pricing tests, acquisition channels, content strategy, and conversion experiments.",
    status: "planning",
    priority: "medium",
    progress: 20,
    milestones: [
      { label: "Free tier model drafted", done: true },
      { label: "Landing page A/B test", done: false },
      { label: "Content calendar launched", done: false },
    ],
    nextMilestone: "Landing page A/B test",
    lastUpdated: new Date(Date.now() - 24 * 3600000).toISOString(),
    color: "--brain-purple",
  },
  {
    id: "proj-5",
    name: "Personal Operations",
    description: "Health, travel, personal admin, and life logistics that keep everything running.",
    status: "on_track",
    priority: "low",
    progress: 75,
    milestones: [
      { label: "Dentist rescheduled", done: false },
      { label: "Toronto flight booked", done: false },
      { label: "Gym routine set", done: true },
    ],
    nextMilestone: "Dentist rescheduled",
    lastUpdated: new Date(Date.now() - 3 * 3600000).toISOString(),
    color: "--brain-rose",
  },
];
