// Re-export the canonical Supabase client from @/lib/supabase/client.
// Having two separate createClient() calls produces the
// "Multiple GoTrueClient instances detected" warning, so we delegate
// to the single source of truth.
//
// This file used to be auto-generated by Lovable; if it gets regenerated,
// re-apply this re-export so we keep one client instance.

export { supabase, isSupabaseEnabled } from "@/lib/supabase/client";
export type { Database } from "./types";
